#!/usr/bin/python

import os
from os import listdir, path
from os.path import isfile, join

import shutil

model_config="""<?xml version="1.0"?>
<model>
  <name>{0}</name>
  <version>1.0</version>
 <sdf version='1.4'>urdf/{0}.urdf</sdf> 

  <author>
   <name>Benjamin Brieber</name>
   <email>bbrieber@cs.uni-bremen.de</email>
  </author>

  <description>
    {0}
    Autogenerated by gazebo simple ros model creator
  </description>
</model>
"""

xacro_template="""<?xml version="1.0"?>

<robot name="{1}" xmlns:xacro="http://ros.org/wiki/xacro">
    
      
    <xacro:macro name="{1}">
      <link name="base_link">
      <inertial>
        <mass value="1" />
        <origin xyz="0 0 0" />
        <inertia ixx="0" ixy="0.0" ixz="0.0" iyy="0." iyz="0.0" izz="0.0" />
      </inertial>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0" />
	  <geometry>
	    <mesh filename="package://{2}/{1}/meshes/{0}"/>
	  </geometry>
	</visual>

	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0" />
	  <geometry>
	    <mesh filename="package://{2}/{1}/meshes/{0}"/>
	  </geometry>
	</collision>
      </link>
    </xacro:macro>

    <xacro:{1}/>
    <gazebo> 
      <static>true</static>
    </gazebo>
</robot>
"""
urdf_template="""<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from {1}.urdf.xacro           | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="{1}" xmlns:xacro="http://ros.org/wiki/xacro">
  <link name="base_link">
    <inertial>
      <mass value="1"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0" ixy="0.0" ixz="0.0" iyy="0." iyz="0.0" izz="0.0"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://{2}/{1}/meshes/{0}"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://{2}/{1}/meshes/{0}"/>
      </geometry>
    </collision>
  </link>
  <gazebo>
    <static>true</static>
  </gazebo>
</robot>
"""

mypath = '/home/bbrieber/workspace/src/iai_rescue_environment/models/environment/tmp'
package_path = 'iai_rescue_environment/models/environment'
#os.getcwd()

files = [ f for f in listdir(mypath) if isfile(join(mypath,f)) ]
endings= ['dae','stl','DAE']

for file in files:
  file_parts = file.split('.')
  if len(file_parts) != 2:
    print("len error")
    continue
  if not file_parts[1] in endings:
    print("file type not recognized")
    continue
  pkg_path = mypath+os.sep+ file_parts[0].lower()
  print(pkg_path)
  if not os.path.exists(pkg_path):
    os.makedirs(pkg_path)
    os.makedirs(pkg_path+os.sep+"meshes")
    os.makedirs(pkg_path+os.sep+"urdf")
  out = open(pkg_path+os.sep+"model.config", "w")
  out.write(model_config.format(file_parts[0].lower()))
  out.close()
  print(mypath+os.sep+file)
  shutil.copyfile(mypath+os.sep+file,pkg_path+os.sep+"meshes"+os.sep+file)
  
  out = open(pkg_path+os.sep+"urdf"+os.sep+file_parts[0].lower()+".urdf", "w")
  out.write(urdf_template.format(file,file_parts[0].lower(),package_path))
  out.close()
  
  
  out = open(pkg_path+os.sep+"urdf"+os.sep+file_parts[0].lower()+".urdf.xacro", "w")
  out.write(xacro_template.format(file,file_parts[0].lower(),package_path))
  out.close()
  
  